### ISSUE TITLE
[Bug] Compilation error in some deck.gl examples

### ISSUE THREAD

**Issue by lsdch** [visgl/deck.gl#9869]
### Description

[Hexagon layer](https://deck.gl/examples/hexagon-layer) example gives this compilation error : 
```
luma.gl: Link error during link-error: Must have a compiled vertex shader attached:
SHADER_INFO_LOG:
0(23) : error C7532: global function uintBitsToFloat requires "#version 330" or later
0(23) : error C0000: ... or #extension GL_ARB_shader_bit_encoding : enable
0(23) : error C0000: ... or #extension GL_ARB_gpu_shader5 : enable
```

Base map layer and control panel are displayed correctly, but hexagon layer is missing (as expected since an error was thrown).
An overlay with details about the faulty shader is displayed (see logs section).
Bug is not reproduced when using Chromium instead of Firefox (see Environment section).

Looks similar to #9638, though the other issue reports this bug on LibreWolf browser and no problems when using Firefox.

The exact same error occurs on [contour layer](https://deck.gl/examples/contour-layer) example. Other examples work fine.

### Flavors

- [ ] Script tag
- [x] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CARTO
- [ ] ArcGIS

### Steps to Reproduce

- The issue seems to be specific to this particular setup (Linux Mint with official NVIDIA driver + Firefox). 
- Works fine on the same OS, when using Chromium browser
- Works fine on Windows + Firefox 145.0
- Works fine on another machine running Linux Mint 21 with Intel graphics chip + Firefox

Firefox configuration was NOT tweaked in any way regarding WebGL. Every relevant system components (NVIDIA config, firefox, webgl...) runs pretty much on default settings.

### Environment

- Framework version: deck.gl@9.2.2
- Browser: Firefox 145.0
- OS: Linux Mint 22.2
- Kernel: 6.14.0-35-generic
- GPU: NVIDIA GeForce RTX 2060/PCIe/SSE2
- NVIDIA Driver Version: 570.195.03
- OpenGL : 
  - is enabled in the browser
  - logging WebGL2 shading language version from the browser console gives `WebGL GLSL ES 3.00`

### Logs

Example page for hexagon layer displays an overlay with the following infos : 

----

**Compilation error in vertex shader "buffer-transform-model-vertex"**
```
   1: #version 300 es
   2: 
   3: // ----- PROLOGUE -------------------------
   4: #define SHADER_TYPE_VERTEX
   5: 
   6: #define NVIDIA_GPU
   7: // Nvidia optimizes away the calculation necessary for emulated fp64
   8: #define LUMA_FP64_CODE_ELIMINATION_WORKAROUND 1
   9: 
  10: 
  11: 
  12: // ----- APPLICATION DEFINES -------------------------
  13: 
  14: #define NUM_DIMS 2
  15: #define NUM_CHANNELS 2
  16: #define SAMPLER_WIDTH 1024
  17: 
  18: 
  19: // ----- MODULE geometry ---------------
  20: 
  21: #define MODULE_GEOMETRY
  22: #define SMOOTH_EDGE_RADIUS 0.5
  23: 
  24: struct VertexGeometry {
  25:   vec4 position;
  26:   vec3 worldPosition;
  27:   vec3 worldPositionAlt;
  28:   vec3 normal;
  29:   vec2 uv;
  30:   vec3 pickingColor;
  31: } geometry = VertexGeometry(
  32:   vec4(0.0, 0.0, 1.0, 0.0),
  33:   vec3(0.0),
  34:   vec3(0.0),
  35:   vec3(0.0),
  36:   vec2(0.0),
  37:   vec3(0.0)
  38: );
  39: 
  40: // ----- MODULE aggregatorTransform ---------------
  41: 
  42: #define MODULE_AGGREGATORTRANSFORM
  43: uniform aggregatorTransformUniforms {
  44:   ivec4 binIdRange;
  45:   bvec3 isCount;
  46:   bvec3 isMean;
  47:   float naN;
  48: } aggregatorTransform;
  49: 
  50: // ----- MAIN SHADER SOURCE -------------------------
  51: 
  52: 
  53: void DECKGL_FILTER_SIZE(inout vec3 size, VertexGeometry geometry) {
  54: }
  55: void DECKGL_FILTER_GL_POSITION(inout vec4 position, VertexGeometry geometry) {
  56: }
  57: void DECKGL_FILTER_COLOR(inout vec4 color, VertexGeometry geometry) {
  58: }
  59: #define SHADER_NAME gpu-aggregation-domain-vertex
  60: 
  61: uniform sampler2D bins;
  62: 
  63: #if NUM_DIMS == 1
  64: out float binIds;
  65: #else
  66: out vec2 binIds;
  67: #endif
  68: 
  69: #if NUM_CHANNELS == 1
  70: flat out float values;
  71: #elif NUM_CHANNELS == 2
  72: flat out vec2 values;
  73: #else
  74: flat out vec3 values;
  75: #endif
  76: 
  77: const float NAN = intBitsToFloat(-1);
  78: 
  79: void main() {
  80:   int row = gl_VertexID / SAMPLER_WIDTH;
  81:   int col = gl_VertexID - row * SAMPLER_WIDTH;
  82:   vec4 weights = texelFetch(bins, ivec2(col, row), 0);
  83:   vec3 value3 = mix(
  84:     mix(weights.rgb, vec3(weights.a), aggregatorTransform.isCount),
  85:     weights.rgb / max(weights.a, 1.0),
  86:     aggregatorTransform.isMean
  87:   );
  88:   if (weights.a == 0.0) {
  89:     value3 = vec3(NAN);
  90:   }
  91: 
  92: #if NUM_DIMS == 1
  93:   binIds = float(gl_VertexID + aggregatorTransform.binIdRange.x);
  94: #else
  95:   int y = gl_VertexID / (aggregatorTransform.binIdRange.y - aggregatorTransform.binIdRange.x);
  96:   int x = gl_VertexID - y * (aggregatorTransform.binIdRange.y - aggregatorTransform.binIdRange.x);
  97:   binIds.y = float(y + aggregatorTransform.binIdRange.z);
  98:   binIds.x = float(x + aggregatorTransform.binIdRange.x);
  99: #endif
 100: 
 101: #if NUM_CHANNELS == 3
 102:   values = value3;
 103: #elif NUM_CHANNELS == 2
 104:   values = value3.xy;
 105: #else
 106:   values = value3.x;
 107: #endif
 108: 
 109:   gl_Position = vec4(0., 0., 0., 1.);
 110:   // This model renders into a 2x1 texture to obtain min and max simultaneously.
 111:   // See comments in fragment shader
 112:   gl_PointSize = 2.0;
 113: }
 INFO: 
 INFO: enable
 INFO: enable


Translated Source


#version 150
#extension GL_ARB_explicit_attrib_location : require
layout(std140) uniform webgl_3904161b1e9671f{
  ivec4 webgl_d2e2a19a64293bbd;
  bvec3 webgl_9b654fc050ac2af9;
  bvec3 webgl_6cf504e7f8f693ac;
  float webgl_c2c164873d9d9a2e;
} webgl_25eddf4f3f68b4b1;
uniform sampler2D webgl_34366715d1e069f4;
out vec2 webgl_a36934639df838a0;
flat out vec2 webgl_19b312f042795e4d;
void main(){
  (gl_PointSize = 0.0);
  (gl_Position = vec4(0.0, 0.0, 0.0, 0.0));
  (webgl_19b312f042795e4d = vec2(0.0, 0.0));
  (webgl_a36934639df838a0 = vec2(0.0, 0.0));
  int webgl_48485d1fdc288126 = (gl_VertexID / 1024);
  int webgl_5a71a30409cd6bd6 = (gl_VertexID - (webgl_48485d1fdc288126 * 1024));
  vec4 webgl_d6afe43b4ef75be3 = texelFetch(webgl_34366715d1e069f4, ivec2(webgl_5a71a30409cd6bd6, webgl_48485d1fdc288126), 0);
  vec3 webgl_20ce1816b2b03900 = mix(mix(webgl_d6afe43b4ef75be3.xyz, vec3(webgl_d6afe43b4ef75be3.w), webgl_25eddf4f3f68b4b1.webgl_9b654fc050ac2af9), (webgl_d6afe43b4ef75be3.xyz / max(webgl_d6afe43b4ef75be3.w, 1.0)), webgl_25eddf4f3f68b4b1.webgl_6cf504e7f8f693ac);
  if ((webgl_d6afe43b4ef75be3.w == 0.0))
  {
    (webgl_20ce1816b2b03900 = vec3(uintBitsToFloat(4294967295u), uintBitsToFloat(4294967295u), uintBitsToFloat(4294967295u)));
  }
  int webgl_7d67e5119856dd1b = (gl_VertexID / (webgl_25eddf4f3f68b4b1.webgl_d2e2a19a64293bbd.y - webgl_25eddf4f3f68b4b1.webgl_d2e2a19a64293bbd.x));
  int webgl_350702f5a0424893 = (gl_VertexID - (webgl_7d67e5119856dd1b * (webgl_25eddf4f3f68b4b1.webgl_d2e2a19a64293bbd.y - webgl_25eddf4f3f68b4b1.webgl_d2e2a19a64293bbd.x)));
  (webgl_a36934639df838a0.y = float((webgl_7d67e5119856dd1b + webgl_25eddf4f3f68b4b1.webgl_d2e2a19a64293bbd.z)));
  (webgl_a36934639df838a0.x = float((webgl_350702f5a0424893 + webgl_25eddf4f3f68b4b1.webgl_d2e2a19a64293bbd.x)));
  (webgl_19b312f042795e4d = webgl_20ce1816b2b03900.xy);
  (gl_Position = vec4(0.0, 0.0, 0.0, 1.0));
  (gl_PointSize = 2.0);
}
```

**Comment by chrisgervang** [comment]
Hi @lsdch, the maintainers won't be able to reproduce your desktop environment so please help us isolate this issue further. I want to understand if this is a new bug, or long standing one. Easiest way to test this would be to have you run the website locally and report back any issues.

My recommendation would be the following test: 
- Run deck 9.2.2 website locally (baseline: reproduce the issue in the local dev environment)
- Run deck 8.9 website locally (is this a long-standing issue, or major release issue?)
- If there isn't an issue in 8.9, run deck 9.1 locally

```bash
# Test deck.gl v9.2.2 (baseline - reproduce the issue)
git checkout v9.2.2
yarn bootstrap
cd website
yarn
yarn start
# Open browser and test for the issue

# Test deck.gl v8.9.36 (check if it's a long-standing issue)
cd ..
git checkout v8.9.36
yarn bootstrap
cd website
yarn
yarn start
# Open browser and test for the issue

# If issue NOT present in 8.9, test deck.gl v9.1.15
cd ..
git checkout v9.1.15
yarn bootstrap
cd website
yarn
yarn start
# Open browser and test for the issue

# If issue IS present in 9.1, test deck.gl v9.0.41
cd ..
git checkout v9.0.41
yarn bootstrap
cd website
yarn
yarn start
# Open browser and test for the issue

# When done testing, return to your original branch
git checkout -
```

**Comment by chrisgervang** [comment]
Please pull down #9879 and give it a test (same test as above, running the website on `fix/9869-shader-nan-compatibility` branch). The robot had an idea.. I'm not sure if it's any good.

One curiosity is seeing this is your logs:

```
Translated Source

#version 150
...
``` 

There might be some other issue if that means the program didn't compile to GLSL 3.

**Comment by chrisgervang** [comment]
I'm leaning hard on the robot for knowledge about your system. It's suggesting this explanation

```
Here's what's happening:

  The Transpilation Problem:

  1. Source shader: #version 300 es (GLSL ES 3.00 / WebGL 2) with intBitsToFloat(-1)
  2. Firefox/ANGLE transpiles to: #version 150 (GLSL 1.50 / OpenGL 3.2) with uintBitsToFloat(4294967295u)
  3. The issue: GLSL 1.50 doesn't natively support uintBitsToFloat - it requires either:
    - GLSL 3.30+ (#version 330), OR
    - Extension GL_ARB_shader_bit_encoding, OR
    - Extension GL_ARB_gpu_shader5

  Firefox's ANGLE implementation is transpiling the shader down to an older GLSL version (probably for compatibility with the NVIDIA driver/OpenGL
  implementation), but it's generating code that uses functions not available in that version without enabling the required extensions.

  Why this is browser/driver specific:

  - Chrome's ANGLE implementation might handle this differently (enable the extensions, or transpile to a higher version)
  - Different GPU drivers report different OpenGL capabilities, affecting how ANGLE transpiles
```

The challenge here is that standards are only as good as their implementation. We'll just need to evaluate if using `0.0 / 0.0` fixes your issue _and_ produces the same output across all environments.

**Comment by lsdch** [comment]
Hi @chrisgervang,

First of all, thank you for helping on this issue 🙏

Here is what I got from trying to run the website locally :

- **v9.2.2**
  - `yarn bootstrap` ✅
  - `cd website && yarn` ✅
  - `yarn start` ❌ gives some webpack import errors, and runtime error on the example webpage:
    ```
    ERROR
    _luma_gl_core__WEBPACK_IMPORTED_MODULE_5__.luma.registerDevices is not a function
    ```
  - Installation logs with errors: [v9.2.2.log](https://github.com/user-attachments/files/23680439/v9.2.2.log)
- **v8.9.36** ❌
  - `yarn bootstrap` ❌ gives g++ compile error on `gl` : [v8.9.36.log](https://github.com/user-attachments/files/23680320/v8.9.36.log)
- **v9.1.15** ❌
  - `yarn bootstrap` ✅
  - `cd website && yarn` ✅
  - `yarn start` ❌ gives some webpack import errors, and runtime error on the example webpage:
    ```
    ERROR in ../modules/core/dist/effects/post-process-effect.js 1:215-236
    export 'normalizeShaderModule' (imported as 'normalizeShaderModule') was not found in '@luma.gl/shadertools'
    ```
  - Installation logs with error: [v9.1.15.log](https://github.com/user-attachments/files/23680128/v9.1.15.log)


- **v9.0.41** ✅
  - `yarn bootstrap` ✅ **seems to do a lot more stuff, compared to other versions** (see logs)
  - `cd website && yarn` ✅
  - `yarn start` ✅
  - Hexagon layer example : __WORKS__ ✅
  - Installation logs : [v9.0.41.log](https://github.com/user-attachments/files/23680692/v9.0.41.log)

- **`fix/9869-shader-nan-compatibility`** ❌
  - `yarn bootstrap` ✅
  - `cd website && yarn` ✅
  - `yarn start` ❌ gives some webpack import errors, and runtime error on the example webpage:
    ```
    ERROR
    _luma_gl_core__WEBPACK_IMPORTED_MODULE_5__.luma.registerDevices is not a function
    ```
  - Installation logs with errors: [shader-fix.log](https://github.com/user-attachments/files/23680232/shader-fix.log)

Good news is `v9.0.41` works with my setup. It is surprising that for other versions, I cannot reproduce the same error that was initially reported in this issue: we get webpack import errors instead of a shader error.

Here are some infos about my local JS toolkit, although I don't think it's really messing with anything here:
```
❯ nvm version
v20.19.5
❯ yarn version
yarn version v1.22.18
```

Let me know if there are other things I can try. Thanks !

**Comment by chrisgervang** [comment]
Looks like the website is showing unrelated JavaScript errors. Let's try a simpler example. Also, I realized the website may not apply the branch's local patch 

Can you try this app on the versions that had issues?

```
cd /examples/website/3d-heatmap
yarn
yarn start-local
```

This is this hexagon layer example on the site as a standalone project.

Interesting to hear it worked on v9. I think that extra stuff in bootstrap was split out to 
`yarn build`. If you continue to have local issues unrelated to the shader one, try running build on the top level (that said, `start-local` is designed to use module sources directly rather than build artifacts.. but building won't hurt anything)

**Comment by ibgreen** [comment]
Worth making sure that your install doesn't mix package versions. Maybe go to root and run:

grep -R "deck.gl" yarn.lock
grep -R "luma.gl" yarn.lock

You could also try to remove yarn.lock in root and website and do clean installs and see if anything changes.

**Comment by lsdch** [comment]
> ```
> cd /examples/website/3d-heatmap
> yarn
> yarn start-local
> ```

Nice, that works ! Well I mean I could reproduce the compilation error, both in v9.1 and v9.2. Unfortunately, the shader fix does not solve this bug: version is still 150 in the transpiled source, although the patch was applied (can confirm `const float NAN = 0.0 / 0.0;` does appear in the source).

v9.0 still works using this method.

---

> Worth making sure that your install doesn't mix package versions. Maybe go to root and run:
> 
> grep -R "deck.gl" yarn.lock 
> grep -R "luma.gl" yarn.lock

`grep -R "deck.gl" yarn.lock` gives no output
`grep -R "luma.gl" yarn.lock` on `v9.2.2` : 
```
❯ grep -R "luma.gl" yarn.lock
"@luma.gl/constants@9.2.2", "@luma.gl/constants@^9.2.2":
  resolved "https://registry.yarnpkg.com/@luma.gl/constants/-/constants-9.2.2.tgz#90217c1193a5faf5a94a4bc9623413aa0d5a7f1e"
"@luma.gl/constants@^9.0.0":
  resolved "https://registry.yarnpkg.com/@luma.gl/constants/-/constants-9.0.27.tgz#65d65fa1ea407fd5f74bfa92dfba43261be33763"
"@luma.gl/core@^9.2.2":
  resolved "https://registry.yarnpkg.com/@luma.gl/core/-/core-9.2.2.tgz#89d785f1f6b29002a42aae3842f405b3bd24faaa"
"@luma.gl/effects@^9.2.2":
  resolved "https://registry.yarnpkg.com/@luma.gl/effects/-/effects-9.2.2.tgz#56739b413d974e8846803ed9d6f228f27790ecaf"
"@luma.gl/engine@^9.2.2":
  resolved "https://registry.yarnpkg.com/@luma.gl/engine/-/engine-9.2.2.tgz#a08083e30e14a1da45209523ed682e2c33ff149b"
"@luma.gl/gltf@^9.2.2":
  resolved "https://registry.yarnpkg.com/@luma.gl/gltf/-/gltf-9.2.2.tgz#20594297b9e05cb016b5b4704b84ba6f5beabd5a"
"@luma.gl/shadertools@^9.2.2":
  resolved "https://registry.yarnpkg.com/@luma.gl/shadertools/-/shadertools-9.2.2.tgz#3dafd16e9ca04e901ca2359bcb3bf88f5fb88f6c"
"@luma.gl/test-utils@^9.2.2":
  resolved "https://registry.yarnpkg.com/@luma.gl/test-utils/-/test-utils-9.2.2.tgz#c029e85258ee1443be061c86003b29288ca5c8f2"
"@luma.gl/webgl@^9.2.2":
  resolved "https://registry.yarnpkg.com/@luma.gl/webgl/-/webgl-9.2.2.tgz#fa86453ad0716c8e05cbdaa334b59f130b8efc05"
    "@luma.gl/constants" "9.2.2"
"@luma.gl/webgpu@^9.2.2":
  resolved "https://registry.yarnpkg.com/@luma.gl/webgpu/-/webgpu-9.2.2.tgz#6e334810c8a0c22864652e4dd08e747e8e912e64"
    "@luma.gl/constants" "^9.0.0"
```


> You could also try to remove yarn.lock in root and website and do clean installs and see if anything changes.

Tried this with `v9.2.2`, still getting import errors. But I guess that's okay, since we now have a way to reproduce the bug through `examples/website/3d-heatmap`.

**Comment by lsdch** [comment]
So I tried switching my GPU drivers and running the example with `v9.2.2`. Using the open source drivers available on Linux Mint solve the problem (`xserver-xorg-video-nouveau v1.0.17-2ubuntu0.1`). 

Using any other NVIDIA driver among  those available to my setup (`nvidia-driver-580-open`, `nvidia-driver-570-open`, `nvidia-driver-535`, `nvidia-driver-470-open`) brings up the bug.

Just in case this helps narrow it down.

**Comment by chrisgervang** [comment]
The bug seems to be in the NVIDIA rather than in deck. I don't think the maintainers will be able to narrow this down further as the root cause is driver related. 

I suspect the reason v9 worked for you was because we disabled features in the initial v9 release, like GPU aggregation, while we transitioned through the major release. My guess is it broke after we re-enabled features present in 8.9.

Feel free to open a PR if you find a smoking gun, but I don't think we will be able to support this.
