### ISSUE TITLE
viewport.projectionMatrix.transform is not a function

### ISSUE THREAD

**Issue by ctaylor4874** [visgl/deck.gl#6350]
#### Description

Arclayer and column layer throwing error with version 8.6.0

React Version: `16.14.0`
Mapbox: Using react-map-gl

#### Environment
 - Framework Version: deck.gl 8.6.0
 - Browser Version: Chrome 95.0.4638.54
 - OS: Mac OS X 12.0.1

#### Logs

<img width="751" alt="Screen Shot 2021-11-02 at 9 41 52 AM" src="https://user-images.githubusercontent.com/8881198/139869326-83faa5f3-15d8-477e-8d74-237538317a34.png">

**Comment by Pessimistress** [comment]
The live demos in example and docs on the website are using the latest version. If you can't get a layer working at all you need to provide a Codepen/Sandbox that reproduces your issue.

**Comment by daaain** [comment]
I don't have a repro yet, but same thing happened to me with `8.6.1`, works with `8.5.10`.

Will post if I have more info.

**Comment by ctaylor4874** [comment]
Yes I can’t reproduce in Codepen for some reason, but downgrading to 8.5.10 fixes the issue for me as well

**Comment by Pessimistress** [comment]
This should no longer be an issue in v8.6.4. Reopen if able to reproduce.
