### ISSUE TITLE
[Bug] Can't compile after updating to deck.gl 9.0.1 (regression)

### ISSUE THREAD

**Issue by ruizmarc** [visgl/deck.gl#8711]
### Description

I cannot compile application with deck.gl 9.0.1. I could compile without any problem with previous version 8.9.21.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

I should be able to compile the application

### Steps to Reproduce

I have an angular application using deck.gl, and when I try to compile it, it crashes with the error shown in logs. 

I tried both webpack builder and application builder with esbuild, but I get the same error. I tried both angular 16 and angular 17. In both cases crashes with deck.gl 9.0.1 and it works fine with 8.9.21.

I'm using using different layers such as Heatmap, IconLayer, TextLayer and ScatterplotLayer.

### Environment

Deps:
"@deck.gl/aggregation-layers": "^9.0.1",
"@deck.gl/core": "^9.0.1",
"@deck.gl/google-maps": "^9.0.1",
"@deck.gl/layers": "^9.0.1",
    
- Framework version: Angular 16 and Angular 17
- Browser: Any
- OS: Any

### Logs

 Application bundle generation failed. [27.793 seconds]
 
 ✘ [ERROR] TS2307: Cannot find module 'modules/core/src/lib/attribute/attribute' or its corresponding type declarations. [plugin angular-compiler]
 
     node_modules/@deck.gl/aggregation-layers/dist/aggregation-layer.d.ts:16:29:
       16 │ ...ring]: import("modules/core/src/lib/attribute/attribute").default;
          ╵                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 
 ✘ [ERROR] TS2307: Cannot find module '../...js' or its corresponding type declarations. [plugin angular-compiler]
 
     node_modules/@luma.gl/core/dist/adapter/resources/render-pass.d.ts:5:28:
       5 │ import { NumberArray } from "../...js";
         ╵                             ~~~~~~~~~~
 
 
 ✘ [ERROR] TS2307: Cannot find module '../...js' or its corresponding type declarations. [plugin angular-compiler]
 
     node_modules/@luma.gl/core/dist/adapter/type-utils/vertex-format-from-attribute.d.ts:1:50:
       1 │ import { TypedArray, TypedArrayConstructor } from "../...js";
         ╵                                                   ~~~~~~~~~~
 
 
 ✘ [ERROR] TS2307: Cannot find module '../...js' or its corresponding type declarations. [plugin angular-compiler]
 
     node_modules/@luma.gl/shadertools/dist/modules-webgl1/project/project.d.ts:1:29:
       1 │ import { ShaderModule } from "../...js";
         ╵                              ~~~~~~~~~~

**Comment by donmccurdy** [comment]
>  node_modules/@deck.gl/aggregation-layers/dist/aggregation-layer.d.ts:16:29:
   16 │ ...ring]: import("modules/core/src/lib/attribute/attribute").default;
      ╵                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I'll make a PR for this error. The others  looks like @ibgreen is already on the others with PRs in lumagl.

**Comment by Pessimistress** [comment]
Fixes are published in v9.0.3.
